name: datatest  # Data Testing Tutorial
channels: !!python/tuple
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- colorama
- jupyter
- ipykernel
- jupyterlab
- pytest
- pytest-cov
- tinydb
- pyyaml
- pandas-summary
- pip:
  - environment_kernels
  - missingno
  - rise
